### ISSUE TITLE
[BUG] 关于文本信息的一些错误

### ISSUE THREAD

**Issue by Kalidium** [Rothes/Prism-Bukkit#1]
![`2~F$I39RUZK )0_4$8B2{4](https://user-images.githubusercontent.com/60288144/128139339-aea9de8a-5130-4dcb-a418-e57d65cfe2a8.png)
查询的时候 物品信息过长 有空格

然后就是第一次查询的结果时 下面没有翻页按钮
只能通过输入 /pr page 2 下面才会有翻页功能

**Comment by Rothes** [comment]
已经通过以下提交修复:
https://github.com/Rothes/Prism-Bukkit/commit/ab958bdaaa3dfaa4002d384fe34ee30ca37bf810
https://github.com/Rothes/Prism-Bukkit/commit/5ccae669a15ef705213352a353c9d4c36951059d
https://github.com/Rothes/Prism-Bukkit/commit/7d70798245b4d271d66726dc142ec762f5ad2e53
