### ISSUE TITLE
1.17的spigot端，Prism版本‘Prism 2.1.8-CN-210822-18’，mysql的版本为‘mysql-5.7.28-winx64’

### ISSUE THREAD

**Issue by VK-fgd** [Rothes/Prism-Bukkit#3]
输入/prism undo last 恢复上一次执行的排水操作时控制台显示数据库连接错误怎么解？
[新建文本文档 (2).txt](https://github.com/Rothes/Prism-Bukkit/files/7191029/2.txt)

**Comment by Rothes** [comment]
是插件问题，待我解决

**Comment by Rothes** [comment]
已经通过以下提交修复：
https://github.com/Rothes/Prism-Bukkit/commit/d5817fcc2eeec43acd5b57278955f2454218db04
https://github.com/Rothes/Prism-Bukkit/commit/867e3879fd9accbf29084487920f281939ef08e6

**Comment by Rothes** [comment]
感谢您的反馈，请在mcbbs帖子中更新。

**Comment by VK-fgd** [comment]
好的，感谢大佬

**Comment by VK-fgd** [comment]
好的，感谢大佬

**Comment by VK-fgd** [comment]
不小心把评论删了，实在抱歉
