### ISSUE TITLE
[BUG] 使用指令/pr undo(撤销)的时候出现乱码

### ISSUE THREAD

**Issue by VK-fgd** [Rothes/Prism-Bukkit#4]
> 1.17的spigot端，prism的版本为"Prism 2.1.8-CN-210919-19"

- 使用指令/pr undo(撤销)的时候出现乱码
[乱码.txt](https://github.com/Rothes/Prism-Bukkit/files/7209483/default.txt)

- 撤销上一步操作失败（不知道这算不算个问题）
![1](https://user-images.githubusercontent.com/90676409/134296186-34c5f216-3b2c-48b9-8c38-804faac81143.png)
![2](https://user-images.githubusercontent.com/90676409/134296202-da0d94e5-2412-417e-8194-99da7963b29f.png)

**Comment by Rothes** [comment]
您上传的文件无法加载，请重新上传或者使用 [Pastebin](https://pastebin.ubuntu.com/)。
此功能经过我测试是可以正常工作的。

**Comment by Rothes** [comment]
您上传的文件无法加载，请重新上传或者使用 [Pastebin](https://pastebin.ubuntu.com/)。
此功能经过我在 Paper 上测试是可以正常工作的。
如果确实不可生效，请使用 /prism debug on 后执行操作，调试信息能够帮助我修复该问题。

**Comment by VK-fgd** [comment]
> 您上传的文件无法加载，请重新上传或者使用 [Pastebin](https://pastebin.ubuntu.com/)。
> 此功能经过我在 Paper 上测试是可以正常工作的。
> 如果确实不可生效，请使用 /prism debug on 后执行操作，调试信息能够帮助我修复该问题。

好的，已再次上传。

**Comment by Rothes** [comment]
> > 您上传的文件无法加载，请重新上传或者使用 [Pastebin](https://pastebin.ubuntu.com/)。
> > 此功能经过我在 Paper 上测试是可以正常工作的。
> > 如果确实不可生效，请使用 /prism debug on 后执行操作，调试信息能够帮助我修复该问题。
> 
> 好的，已再次上传。

这个错误的原因是我上次的更新破坏了之前的数据读取方式，现在的撤销操作不可撤销上次更新的版本之前的排水操作，但是可以正常查询。
这个版本之后的排水操作是可以撤销的。

**Comment by Rothes** [comment]
如果您没有其他需求，我将关闭此议题。

**Comment by VK-fgd** [comment]
好的谢谢
